Accept=Onartu
Close=Itxi
Price= Prezioa
SelectOption=Aukeratu
Lenguage=Hizkuntza


MainGUI.QuerySales= Eskaintzak konstsultatu
MainGUI.MainTitle=Merkatua
MainGUI.Login=Saioa Hasi
MainGUI.Register=Erregistratu
MainGUI.Guest=Gonbidatzailea


LoginGUI.UsernameLabel=Erabiltzailea:
LoginGUI.PasswordLabel=Pasahitza:
LoginGUI.btnLogin=SAIOA HASI
LoginGUI.WrongCredentials=Kredentzial okerrak
LoginGUI.EmptyFields=Hutsune hutsak
LoginGUI.MainTitle=Sesioa Hasten


RegisterGUI.UsernameLabel=Erabiltzailea:
RegisterGUI.PasswordLabel=Pasahitza:
RegisterGUI.PasswordLabelRepeat=Pasahitza errepikatu:
RegisterGUI.btnSignUp=ERREGISTRATU
RegisterGUI.UserAlreadyExists=Erabiltzailea jada existitzen da
RegisterGUI.DiferentPasswords=Pasahitzak ez dira berdinak
RegisterGUI.EmptyFields=Hutsune hutsak
RegisterGUI.MainTitle=Erregistratzen


RegisteredGUI.CreateSale=Eskaintza sortu
RegisteredGUI.QuerySales=Eskaintzak konstsultatu
RegisteredGUI.Profile=Profila
RegisteredGUI.MainTitle=Erregistratua: 


ProfileGUI.MainTitle=Profila
ProfileGUI.LogOut=Saiotik atera
ProfileGUI.Balance=Saldoa
ProfileGUI.AddMoney=Dirua gehitu
ProfileGUI.WithdrawMoney=Dirua atera
ProfileGUI.InvalidAmount=Sartu 0 baino handiagoa den kopuru balioduna
ProfileGUI.AddedMoney=Dirua ondo gehitu da
ProfileGUI.WithdrawOk=Dirua ondo atera da
ProfileGUI.WithdrawError=Saldo nahikorik ez


CreateSaleGUI.Title=Tituloa
CreateSaleGUI.Description=Deskripzioa
CreateSaleGUI.Status=Egoera
CreateSaleGUI.Category=Kategoria
CreateSaleGUI.Price=Prezioa
CreateSaleGUI.PriceMustBeGreaterThan0=ERROR, prezioa 0 baino handiagoa
CreateSaleGUI.ProductCreated=Eskaintza sortuta
CreateSaleGUI.CreateProduct=Sortu Eskaintza
CreateSaleGUI.ErrorNumber=Error, prezioa zenbaki bat izan behar da
CreateSaleGUI.ErrorQuery=Error, datuak falta dira
CreateSaleGUI.LoadPicture=Argazkia igo
CreateSaleGUI.PublicationDate=Argitarapen eguna

QuerySalesGUI.Search=Bilatu
QuerySalesGUI.NoProducts=Ez daude eskaintzak
QuerySalesGUI.Price=Prezioa
QuerySalesGUI.FindProducts=Eskaintzak bilatu
QuerySalesGUI.Products=Eskaintzak (Double-click eskaintza ikusteko)


ShowSaleGUI.AddtoFav=Favoritoa
ShowSaleGUI.Buy=Erosi
ShowSaleGUI.Buyed=Erosita
ShowSaleGUI.Title=Eskaintza xehestasunak
ShowSaleGUI.BuyError=Ezin izan da erosketa osatu
ShowSaleGUI.OnlyRegisteredFav=Saioa hasi favoritoa gehitzeko
ShowSaleGUI.MakeOffer=Eskaintza egin
ShowSaleGUI.OfferPrompt=Idatzi zure eskaintzaren kopurua
ShowSaleGUI.InvalidOffer=Sartu 0 baino handiagoa den kopuru balioduna
ShowSaleGUI.OfferCreated=Eskaintza ondo bidali da
ShowSaleGUI.OfferError=Ezin izan da eskaintza bidali
ShowSaleGUI.OnlyRegisteredOffer=Saioa hasi eskaintzak egiteko
ShowSaleGUI.SaleSold=Salmenta hau itxita dago
ShowSaleGUI.YourOwnSale=Ezin duzu zure salmentan eskaintzarik egin
ShowSaleGUI.AcceptOffer=Eskaintza onartu
ShowSaleGUI.SelectOffer=Hautatu eskaintza bat
ShowSaleGUI.NoOffers=Ez dago onartzeko eskaintzarik
ShowSaleGUI.OfferAccepted=Eskaintza ondo onartu da
ShowSaleGUI.AcceptOfferError=Ezin izan da eskaintza onartu


DataAccess.SaleAlreadyExist=ERROR, Eskaintza existizen da
DataAccess.ErrorSaleMustBeLaterThanToday=ERROR, data gaur baino beranduago izan behar da
DataAccess.ErrorFileNotUploadedException=ERROR, Argazkia igo behar da